# yaml-language-server: $schema=https://schemastore.org/github-workflow
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: awalsh128/cache-apt-pkgs-action@553a35bb8ebd9fcabcb1c9451aa4c98e1b4ca8a9
        with:
          packages: pandoc
      - uses: actions/setup-node@main
        with:
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm run man
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
      - uses: actions/setup-node@main
        with:
          registry-url: https://npm.pkg.github.com
          scope: '@${{ github.repository_owner }}'
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish
name: Package
on:
  release:
    types: [created]
permissions:
  contents: read
  packages: write
